### ISSUE TITLE
SSA and generics (go1.18)

### ISSUE THREAD

**Issue by ldez** [kkHAIKE/contextcheck#4]
Currently, SSA is not working with generics.

So your linter produces a panic when it is used with generics.

There is an issue open about that in the Go repository: https://github.com/golang/go/issues/48525

Inside golangci-lint, we have disabled your linters: https://github.com/golangci/golangci-lint/issues/2649

You have 2 solutions:
- waiting for a version of SSA that will support generics
- dropping the SSA analyzers and using something else to analyze the code.

Related to https://github.com/golang/go/issues/50558

**Comment by SVilgelm** [comment]
@sylvia7788 is there any updates on this issue?

**Comment by kkHAIKE** [comment]
I will focus on it now.. 😊

**Comment by kkHAIKE** [comment]
i find another solution [honnef.co/go/tools/go/ir](https://pkg.go.dev/honnef.co/go/tools@v0.3.2/go/ir).
it's modify from official SSA, use in staticcheck, but it's change more behavior...😭
so i think we can wait the next offical SSA. 😎

**Comment by ldez** [comment]
SSA has been updated and it seems to work inside golangci-lint.

**Comment by ldez** [comment]
in fact the problem is still here

**Comment by ldez** [comment]
I did some more extensive testing and the issue seems to be resolved.

**Comment by ldez** [comment]
https://github.com/golangci/golangci-lint/issues/3048

**Comment by kkHAIKE** [comment]
fixed and tested in new version
